name: App Deployment - BackOffice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variable
        run: |
          echo "DEPLOY_URL=${{ secrets.DEPLOY_URL_BACKOFFICE_PROD }}" >> $GITHUB_ENV

      - name: Send Vercel Deploy Webhook
        run: |
          echo "Sending webhook to: $DEPLOY_URL"
          curl -X POST "$DEPLOY_URL"
